name: CI

on:
  push:
    branches: [ main, v1.2 ]
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: imagick
          coverage: xdebug
          tools: phpstan
      - name: Install dependencies
        run: sudo apt-get install tesseract-ocr
      - name: Install composer dependencies
        run: composer update --no-ansi --no-interaction --no-progress
      - name: Run PHPStan
        run: phpstan analyse src
      - name: Run unit tests
        run: vendor/bin/phpunit tests
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker build
        run: docker build . -t nohn/watermeter
      - name: Run Smoke Test
        run: docker run nohn/watermeter:latest php /usr/src/watermeter/public/index.php | grep 1189.3858
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            nohn/watermeter
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub (latest)
        if: github.ref == 'refs/heads/v1.2' && github.repository == 'nohn/watermeter' && github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          pull: true
          push: true
          cache-from: type=registry,ref=nohn/watermeter:latest
          cache-to: type=inline
          tags: nohn/watermeter:latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push to Docker Hub (develop)
        if: github.ref == 'refs/heads/main' && github.repository == 'nohn/watermeter' && github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          pull: true
          push: true
          cache-from: type=registry,ref=nohn/watermeter:develop
          cache-to: type=inline
          tags: nohn/watermeter:develop
          labels: ${{ steps.meta.outputs.labels }}
